.PHONY: dummy_translations extract_translations fake_translations help pull_translations push_translations \


.DEFAULT_GOAL := help

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

quality: ## check coding style with pycodestyle and pylint
	echo 'TODO: Refactor quality checks from .travis.yml into this Makefile'
	exit 1

requirements: ## install development environment requirements
	pip install -r requirements.txt --exists-action w
	pip install -r requirements-dev.txt --exists-action w

test: clean ## run tests in the current virtualenv
	python run_tests.py

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

## Localization targets

extract_translations: ## extract strings to be translated, outputting .po files
	i18n_tool extract

compile_translations: ## compile translation files, outputting .mo files for each supported language
	django-admin compilemessages

detect_changed_source_translations:
	cd oppia && i18n_tool changed

pull_translations: ## pull translations from POEditor.com
	poeditor pull --config-file django.poeditor
	poeditor pull --config-file djangojs.poeditor
	make compile_translations
	make clean

push_translations: extract_translations ## push source translation files (.po) from POEditor.com
	poeditor pushTerms --config-file django.poeditor
	sleep 11  # Avoid rate limit
	poeditor pushTerms --config-file djangojs.poeditor
	make clean

dummy_translations: ## generate dummy translation (.po) files
	cd oppia && i18n_tool dummy

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

validate_translations: build_dummy_translations detect_changed_source_translations ## validate translations
