.PHONY: dummy_translations extract_translations fake_translations help pull_translations push_translations


.DEFAULT_GOAL := help

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '*.pot' -exec rm -f {} +

	rm -f locale/en/LC_MESSAGES/*

	find oppia/translations -name djangojs.mo -exec rm -f {} +
	find oppia/translations -name djangojs.po -exec rm -f {} +
	find oppia/translations -name textjs.mo -exec rm -f {} +

	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

quality: ## check coding style with pycodestyle and pylint
	echo 'TODO: Refactor quality checks from .travis.yml into this Makefile'
	exit 1

requirements: ## install development environment requirements
	pip install -r requirements.txt --exists-action w
	pip install -r requirements-dev.txt --exists-action w

test: clean ## run tests in the current virtualenv
	python run_tests.py

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

## Localization targets

extract_translations: clean ## extract strings to be translated, outputting .po files
	python manage.py makemessages -l en -d django
	python manage.py makemessages -l en -d djangojs -e js --ignore oppia/static/js/translations
	mv locale/en/LC_MESSAGES/django.po locale/en/LC_MESSAGES/text.po
	mv locale/en/LC_MESSAGES/djangojs.po locale/en/LC_MESSAGES/textjs.po

compile_translations: ## compile translation files, outputting .mo files for each supported language
	django-admin compilemessages
	python manage.py compilejsi18n
	make clean

detect_changed_source_translations: ## determines if the source translation files are up-to-date, otherwise exit with a non-zero code.
	i18n_tool changed

pull_translations: dummy_translations ## pull translations from POEditor.com
	poeditor pull
	make compile_translations
	make clean

push_translations: clean extract_translations ## push source translation files (.po) to POEditor.com
	poeditor --sync-terms pushTerms

dummy_translations: ## generate dummy translation (.po) files
	i18n_tool dummy

build_dummy_translations: extract_translations dummy_translations compile_translations ## generate and compile dummy translation files

validate_translations: build_dummy_translations detect_changed_source_translations ## validate translations
